### ISSUE TITLE
Failed to publish test run data: System.ArgumentException: Unknown test runner

### ISSUE THREAD

**Issue by steffilion** [parasoft/parasoft-findings-vsts#3]
Hi All,

I'm trying to use the plugin and always getting this:
```
2020-03-16T18:40:41.4077914Z ##[warning]Failed to publish test run data: System.ArgumentException: Unknown test runner
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.TestDataPublisher.ParseTestResultsFile(TestRunContext runContext, List`1 testResultFiles)
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.TestDataPublisher.PublishAsync(TestRunContext runContext, List`1 testResultFiles, PublishOptions publishOptions, CancellationToken cancellationToken)
2020-03-16T18:40:41.4113249Z ##[debug]Processed: ##vso[results.publish type=SOAtest9x;mergeResults=false;runTitle=test;publishRunAttachments=true;resultFiles=/home/vsts/workspace/Gandalf_2/13/s/report_Autonomy.xml,/home/vsts/workspace/Gandalf_2/13/s/report_CfD.xml,/home/vsts/workspace/Gandalf_2/13/s/report_CFD.xml;]

```

The way I configured the publiser:
```
- task: PublishTestResults@1
  inputs:
    testRunner: 'SOAtest9x'
    testResultsFiles: '**/*.xml'
    testRunTitle: 'test'
```
I also tried :
```
testRunner: 'XTest10x'
```
With the same result.

Any idea?

What I am missing

**Comment by yshi-parasoft** [comment]
The plugin's functionality has been updated. "testRunner" is not used in the configuration anymore. The problem should no longer occur.
